use crate::{metadata, model::*};
use quote::ToTokens;
use std::{
    fs,
    path::{Path, PathBuf},
};

use super::generator_io::{atomic_write, collect_rs, content_hash};

pub fn scan_inputs(
    inputs: &[PathBuf],
    source: String,
) -> Result<(Catalog, Vec<UnsupportedEntry>), Box<dyn std::error::Error>> {
    let mut files = Vec::new();
    for input in inputs {
        collect_rs(input, &mut files)?;
    }
    if files.is_empty() {
        return Err(format!("no Rust source files found under {source}").into());
    }
    let mut catalog = Catalog {
        schema: 1,
        source,
        types: Vec::new(),
        functions: Vec::new(),
        methods: Vec::new(),
        components: Vec::new(),
        data_types: Vec::new(),
    };
    let mut unsupported = Vec::new();
    for file in files {
        parse_file(&file, &mut catalog, &mut unsupported)?;
    }
    Ok((catalog, unsupported))
}

pub fn write_catalog_artifacts(
    output: &Path,
    catalog: &Catalog,
    unsupported: &[UnsupportedEntry],
) -> Result<(), Box<dyn std::error::Error>> {
    atomic_write(
        &output.join("curated-catalog.json"),
        &serde_json::to_vec_pretty(&metadata::curated_catalog()?)?,
    )?;
    atomic_write(
        &output.join("catalog.json"),
        &serde_json::to_vec_pretty(catalog)?,
    )?;
    atomic_write(
        &output.join("unsupported.json"),
        &serde_json::to_vec_pretty(unsupported)?,
    )?;
    atomic_write(
        &output.join("api-diff.md"),
        format!(
            "# Lua API Diff\n\nGenerated schema: {}\n\nTypes: {}\nFunctions: {}\nMethods: {}\nComponents: {}\nUnsupported items: {}\n",
            catalog.schema,
            catalog.types.len(),
            catalog.functions.len(),
            catalog.methods.len(),
            catalog.components.len(),
            unsupported.len()
        )
        .as_bytes(),
    )?;
    write_generated(&output.join("generated.rs"), catalog)
}

pub fn write_generated(path: &Path, catalog: &Catalog) -> Result<(), Box<dyn std::error::Error>> {
    let catalog_hash = content_hash(&serde_json::to_vec(catalog)?);
    let output = format!(
        "// @generated by lua-tool; do not edit.\n// @source-hash: {catalog_hash:016x}\n\n/// Source catalog metadata generated from Rust AST.\npub const LUA_TOOL_CATALOG_SCHEMA: u32 = {};\npub const LUA_TOOL_CATALOG_HASH: u64 = 0x{catalog_hash:016x};\n",
        catalog.schema
    );
    atomic_write(path, output.as_bytes())
}

pub fn parse_file(
    path: &Path,
    catalog: &mut Catalog,
    unsupported: &mut Vec<UnsupportedEntry>,
) -> Result<(), Box<dyn std::error::Error>> {
    let source = fs::read_to_string(path)?;
    let file = syn::parse_file(&source)?;
    for item in file.items {
        match item {
            syn::Item::Struct(item) if is_public(&item.vis) => catalog.types.push(TypeEntry {
                name: item.ident.to_string(),
                kind: "struct".into(),
                fields: named_fields(&item.fields),
                status: "CatalogOnly",
            }),
            syn::Item::Enum(item) if is_public(&item.vis) => catalog.types.push(TypeEntry {
                name: item.ident.to_string(),
                kind: "enum".into(),
                fields: enum_variants(&item.variants),
                status: "CatalogOnly",
            }),
            syn::Item::Fn(item) if is_public(&item.vis) => catalog.functions.push(FunctionEntry {
                name: item.sig.ident.to_string(),
                signature: quote_signature(&item.sig),
                status: "CatalogOnly",
            }),
            syn::Item::Impl(item) => {
                let owner = item.self_ty.to_token_stream().to_string();
                for method in item.items {
                    if let syn::ImplItem::Fn(method) = method {
                        if is_public(&method.vis) {
                            catalog.methods.push(MethodEntry {
                                owner: owner.clone(),
                                name: method.sig.ident.to_string(),
                                signature: quote_signature(&method.sig),
                                status: "CatalogOnly",
                            });
                        }
                    }
                }
            }
            syn::Item::Trait(item) => unsupported.push(UnsupportedEntry {
                source: path.display().to_string(),
                item: item.ident.to_string(),
                reason: "traits require a handwritten adapter or explicit generator support".into(),
            }),
            syn::Item::Union(item) => unsupported.push(UnsupportedEntry {
                source: path.display().to_string(),
                item: item.ident.to_string(),
                reason: "unions are not safe to expose automatically".into(),
            }),
            _ => {}
        }
    }
    Ok(())
}

fn is_public(vis: &syn::Visibility) -> bool {
    matches!(vis, syn::Visibility::Public(_))
}

fn named_fields(fields: &syn::Fields) -> Vec<String> {
    fields
        .iter()
        .filter_map(|field| field.ident.as_ref().map(ToString::to_string))
        .collect()
}

fn enum_variants(
    variants: &syn::punctuated::Punctuated<syn::Variant, syn::Token![,]>,
) -> Vec<String> {
    variants
        .iter()
        .map(|variant| variant.ident.to_string())
        .collect()
}

fn quote_signature<T: ToTokens>(value: &T) -> String {
    value.to_token_stream().to_string()
}
