use super::generator_io::{atomic_write, content_hash};
use crate::config::ApiConfig;
use std::{collections::BTreeSet, path::Path};

pub fn write_api_registry(
    path: &Path,
    target_name: &str,
    api: &ApiConfig,
) -> Result<(), Box<dyn std::error::Error>> {
    let context_name = api
        .type_name
        .clone()
        .unwrap_or_else(|| format!("{target_name}LuaApis"));
    syn::parse_str::<syn::Ident>(&context_name)
        .map_err(|error| format!("invalid generated API type name '{context_name}': {error}"))?;
    let mut context_names = BTreeSet::new();
    for field in &api.context {
        syn::parse_str::<syn::Ident>(&field.name)
            .map_err(|error| format!("invalid API context field '{}': {error}", field.name))?;
        syn::parse_str::<syn::Type>(&field.rust_type).map_err(|error| {
            format!(
                "invalid Rust type '{}' for API context '{}': {error}",
                field.rust_type, field.name
            )
        })?;
        if !context_names.insert(field.name.as_str()) {
            return Err(format!("duplicate API context field '{}'", field.name).into());
        }
    }
    let fields = api
        .context
        .iter()
        .map(|field| format!("    pub {}: {},\n", field.name, field.rust_type))
        .collect::<String>();
    let known_fields = api
        .context
        .iter()
        .map(|field| field.name.as_str())
        .collect::<BTreeSet<_>>();
    let mut registrations = String::new();
    for registration in &api.registrations {
        syn::parse_str::<syn::Path>(&registration.path).map_err(|error| {
            format!(
                "invalid API registration path '{}': {error}",
                registration.path
            )
        })?;
        for arg in &registration.args {
            if !known_fields.contains(arg.as_str()) {
                return Err(format!(
                    "API registration '{}' references unknown context field '{}'",
                    registration.path, arg
                )
                .into());
            }
        }
        let args = registration
            .args
            .iter()
            .map(|arg| format!("registration_context.{arg}.clone()"))
            .collect::<Vec<_>>()
            .join(", ");
        registrations.push_str(&format!(
            "        let registration_context = context.clone();\n        host.register_game_api_fn(move |lua| {path}(lua{args}))?;\n",
            path = registration.path,
            args = if args.is_empty() {
                String::new()
            } else {
                format!(", {args}")
            },
        ));
    }
    for registration in &api.custom_bindings {
        if !registration
            .path
            .starts_with("lua_plugin::custom_bindings::")
        {
            return Err(format!(
                "custom binding '{}' must reference lua_plugin::custom_bindings::*",
                registration.path
            )
            .into());
        }
        syn::parse_str::<syn::Path>(&registration.path).map_err(|error| {
            format!(
                "invalid custom binding path '{}': {error}",
                registration.path
            )
        })?;
        if !known_custom_binding(&registration.path) {
            return Err(format!(
                "unknown custom binding '{}'; supported bindings are register_component_aliases and register_value_types",
                registration.path
            )
            .into());
        }
        if !registration.args.is_empty() {
            return Err(format!(
                "custom binding '{}' cannot receive business context; put stateful adapters in registrations",
                registration.path
            )
            .into());
        }
        registrations.push_str(&format!(
            "        host.register_custom_binding_fn(|lua| {path}(lua))?;\n",
            path = registration.path,
        ));
    }
    let body = format!(
        "use lua_plugin::LuaPluginHost;\nuse std::rc::Rc;\n\n#[derive(Clone)]\npub struct {context_name} {{\n{fields}}}\n\n/// Registers every configured game or library Lua API in declaration order.\npub fn register_{target_name}_apis(host: &mut LuaPluginHost, context: {context_name}) -> mlua::Result<()> {{\n    let context = Rc::new(context);\n{registrations}    Ok(())\n}}\n",
        context_name = context_name,
        fields = fields,
        target_name = sanitize_ident(target_name),
        registrations = registrations,
    );
    let output = format!(
        "// @generated by lua-tool; do not edit.\n// @source-hash: {:016x}\n{}",
        content_hash(body.as_bytes()),
        body
    );
    atomic_write(path, output.as_bytes())
}

/// Keep the manifest surface explicit.  Custom bindings are engine code and
/// therefore must be reviewed and exported by lua-plugin before a project can
/// select them.  This also turns a misspelled path into a generation error
/// instead of a later Rust compile failure.
fn known_custom_binding(path: &str) -> bool {
    matches!(
        path,
        "lua_plugin::custom_bindings::register_component_aliases"
            | "lua_plugin::custom_bindings::register_value_types"
    )
}

fn sanitize_ident(value: &str) -> String {
    let mut result = value
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '_' {
                ch
            } else {
                '_'
            }
        })
        .collect::<String>();
    if result.is_empty() {
        result.push_str("bindings");
    }
    if result.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        result.insert(0, '_');
    }
    result
}
