//! Offline metadata and binding scaffold generator.
//!
//! This tool intentionally runs outside the game. It reads Rust source files,
//! emits an auditable catalog and generates only registration metadata. Runtime
//! bindings still require approval and either a generated wrapper template or a
//! handwritten implementation in lua-plugin.

mod audit;
mod config;
mod generator;
mod generator_api;
mod generator_io;
mod generator_scan;
mod metadata;
mod model;
use generator::{generate_from_config, generate_scan};
use std::{env, path::PathBuf};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let args = Args::parse(env::args().skip(1))?;
    if let Some(config) = args.config.as_deref() {
        return generate_from_config(config);
    }
    generate_scan(&args.input, &args.output)
}

struct Args {
    config: Option<PathBuf>,
    input: PathBuf,
    output: PathBuf,
}

impl Args {
    fn parse(mut args: impl Iterator<Item = String>) -> Result<Self, Box<dyn std::error::Error>> {
        let mut input = None;
        let mut config = None;
        let mut output = PathBuf::from("target/lua-bindings");
        while let Some(arg) = args.next() {
            match arg.as_str() {
                "--config" => config = args.next().map(PathBuf::from),
                "--input" => input = args.next().map(PathBuf::from),
                "--output" => output = args.next().ok_or("--output requires a directory")?.into(),
                "--runtime-output" => return Err(
                    "--runtime-output was removed; engine bindings are owned by lua-plugin and cannot be generated by lua-tool".into(),
                ),
                "--profile" => {
                    let profile = args.next().ok_or("--profile requires a name")?;
                    if profile != "none" {
                        return Err(
                            "--profile accepts only 'none'; engine bindings belong to lua-plugin"
                                .into(),
                        );
                    }
                }
                "--help" | "-h" => {
                    println!("lua-tool --config <lua-bindings.toml>");
                    println!("lua-tool --input <rust-file-or-dir> [--output <dir>]");
                    std::process::exit(0);
                }
                unknown => return Err(format!("unknown argument: {unknown}").into()),
            }
        }
        Ok(Self {
            config,
            input: input.unwrap_or_else(|| PathBuf::from(".")),
            output,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{config::*, model::*};
    use generator_api::write_api_registry;
    use generator_scan::{parse_file, write_generated};
    use std::fs;

    #[test]
    fn ui_contract_extracts_named_nodes_and_ignores_empty_names() {
        let source = r#"Widget[Name<str:"">] Widget[Name<str:"status_label">] Widget[Name<str:"status_label">]"#;
        assert_eq!(
            audit::extract_ui_names(source),
            vec!["status_label", "status_label"]
        );
    }

    #[test]
    fn extracts_public_types_methods_and_unsupported_items() {
        let path = env::temp_dir().join(format!("lua-tool-{}.rs", std::process::id()));
        fs::write(
            &path,
            "pub struct Sample { pub value: u32 } impl Sample { pub fn get(&self) -> u32 { self.value } } pub trait External {}",
        )
        .unwrap();
        let mut catalog = Catalog {
            schema: 1,
            source: path.display().to_string(),
            types: Vec::new(),
            functions: Vec::new(),
            methods: Vec::new(),
            components: Vec::new(),
            data_types: Vec::new(),
        };
        let mut unsupported = Vec::new();
        parse_file(&path, &mut catalog, &mut unsupported).unwrap();
        assert_eq!(catalog.types[0].name, "Sample");
        assert_eq!(catalog.methods[0].name, "get");
        assert_eq!(unsupported[0].item, "External");
        let _ = fs::remove_file(path);
    }

    #[test]
    fn generated_registration_is_deterministic() {
        let output = env::temp_dir().join(format!("lua-tool-generated-{}.rs", std::process::id()));
        let catalog = Catalog {
            schema: 1,
            source: "test".into(),
            types: vec![TypeEntry {
                name: "Sample".into(),
                kind: "struct".into(),
                fields: vec!["value".into()],
                status: "CatalogOnly",
            }],
            functions: Vec::new(),
            methods: vec![MethodEntry {
                owner: "Sample".into(),
                name: "get".into(),
                signature: "fn get(&self) -> u32".into(),
                status: "CatalogOnly",
            }],
            components: Vec::new(),
            data_types: Vec::new(),
        };
        write_generated(&output, &catalog).unwrap();
        let generated = fs::read_to_string(&output).unwrap();
        assert!(!generated.contains("BindingRegistry"));
        assert!(!generated.contains("CatalogOnly"));
        assert!(!generated.contains("Generated catalog entry"));
        assert!(generated.contains("LUA_TOOL_CATALOG_SCHEMA"));
        assert!(generated.contains("LUA_TOOL_CATALOG_HASH"));
        let _ = fs::remove_file(output);
    }

    #[test]
    fn generated_api_registry_validates_context_and_registration_order() {
        let output = env::temp_dir().join(format!("lua-tool-api-{}.rs", std::process::id()));
        let api = ApiConfig {
            type_name: Some("DemoContext".into()),
            context: vec![ApiContextField {
                name: "state".into(),
                rust_type: "crate::State".into(),
            }],
            registrations: vec![ApiRegistration {
                path: "crate::register_state".into(),
                args: vec!["state".into()],
            }],
            custom_bindings: vec![ApiRegistration {
                path: "lua_plugin::custom_bindings::register_value_types".into(),
                args: Vec::new(),
            }],
        };
        write_api_registry(&output, "demo-api", &api).unwrap();
        let generated = fs::read_to_string(&output).unwrap();
        assert!(generated.contains("pub struct DemoContext"));
        assert!(generated.contains("register_demo_api"));
        assert!(
            generated.contains("crate::register_state(lua, registration_context.state.clone())")
        );
        assert!(generated.contains("register_custom_binding_fn"));
        assert!(generated.contains("lua_plugin::custom_bindings::register_value_types(lua)"));
        let invalid = ApiConfig {
            type_name: None,
            context: Vec::new(),
            registrations: vec![ApiRegistration {
                path: "crate::register_state".into(),
                args: vec!["missing".into()],
            }],
            custom_bindings: Vec::new(),
        };
        assert!(write_api_registry(&output, "invalid", &invalid).is_err());
        let unknown_custom = ApiConfig {
            type_name: None,
            context: Vec::new(),
            registrations: Vec::new(),
            custom_bindings: vec![ApiRegistration {
                path: "lua_plugin::custom_bindings::does_not_exist".into(),
                args: Vec::new(),
            }],
        };
        assert!(write_api_registry(&output, "unknown-custom", &unknown_custom).is_err());
        let _ = fs::remove_file(output);
    }

    #[test]
    fn config_generates_target_catalog_and_api_output() {
        let root = env::temp_dir().join(format!("lua-tool-config-{}", std::process::id()));
        let source_dir = root.join("src");
        fs::create_dir_all(&source_dir).unwrap();
        fs::write(
            source_dir.join("lib.rs"),
            "pub struct Demo { pub value: u32 }",
        )
        .unwrap();
        let config_path = root.join("bindings.toml");
        fs::write(
            &config_path,
            r#"schema = 1
[[targets]]
name = "demo"
inputs = ["src"]
output = "out"
api_output = "demo_bindings.rs"
profile = "none"
[targets.api]
[[targets.api.registrations]]
path = "crate::register_demo"
"#,
        )
        .unwrap();
        generate_from_config(&config_path).unwrap();
        assert!(root.join("out/catalog.json").is_file());
        assert!(root.join("demo_bindings.rs").is_file());
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn empty_project_manifest_is_valid() {
        let root = env::temp_dir().join(format!("lua-tool-empty-config-{}", std::process::id()));
        fs::create_dir_all(&root).unwrap();
        let config = root.join("bindings.toml");
        fs::write(&config, "schema = 1\n").unwrap();
        generate_from_config(&config).unwrap();
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn config_rejects_engine_binding_outputs() {
        let root = env::temp_dir().join(format!("lua-tool-engine-config-{}", std::process::id()));
        fs::create_dir_all(root.join("src")).unwrap();
        fs::write(root.join("src/lib.rs"), "pub struct Demo;").unwrap();
        let config = root.join("bindings.toml");
        fs::write(
            &config,
            r#"schema = 1
[[targets]]
name = "engine"
inputs = ["src"]
output = "out"
runtime_output = "engine.rs"
profile = "common"
"#,
        )
        .unwrap();
        let error = generate_from_config(&config).unwrap_err().to_string();
        assert!(error.contains("engine bindings"));
        let _ = fs::remove_dir_all(root);
    }
}
