// @generated by lua-tool; executable bindings only.
use mlua::Lua;

/// Registers generated common value userdata constructors and fields.
pub fn register_generated_value_types(lua: &Lua) -> mlua::Result<()> {
    crate::game_api::register_value_types(lua)
}

/// Registers executable methods selected by the offline component profile.
pub(crate) fn register_generated_ui_methods<
    M: mlua::UserDataMethods<crate::game_api::UiComponentRef>,
>(
    methods: &mut M,
) {
    methods.add_method("close", |_, this, ()| {
        crate::game_api::queue_ui_command(
            this,
            crate::game_api::UiCommand::SetPopupOpen(this.id.clone(), false),
        )
    });
    methods.add_method("open", |_, this, ()| {
        crate::game_api::queue_ui_command(
            this,
            crate::game_api::UiCommand::SetPopupOpen(this.id.clone(), true),
        )
    });
    methods.add_method("set_checked", |_, this, value: bool| {
        crate::game_api::queue_ui_command(
            this,
            crate::game_api::UiCommand::SetChecked(this.id.clone(), value),
        )
    });
    methods.add_method("set_column", |_, this, value: usize| {
        crate::game_api::queue_ui_command(
            this,
            crate::game_api::UiCommand::SetGridColumn(this.id.clone(), value),
        )
    });
    methods.add_method("set_opacity", |_, this, value: f32| {
        crate::game_api::queue_ui_command(
            this,
            crate::game_api::UiCommand::SetOpacity(this.id.clone(), value),
        )
    });
    methods.add_method("set_progress", |_, this, value: f32| {
        crate::game_api::queue_ui_command(
            this,
            crate::game_api::UiCommand::SetProgress(this.id.clone(), value),
        )
    });
    methods.add_method("set_row", |_, this, value: usize| {
        crate::game_api::queue_ui_command(
            this,
            crate::game_api::UiCommand::SetGridRow(this.id.clone(), value),
        )
    });
    methods.add_method("set_scroll", |_, this, (x, y): (f32, f32)| {
        crate::game_api::queue_ui_command(
            this,
            crate::game_api::UiCommand::SetScroll(this.id.clone(), x, y),
        )
    });
    methods.add_method("set_selected", |_, this, value: Option<usize>| {
        crate::game_api::queue_ui_command(
            this,
            crate::game_api::UiCommand::SetSelected(this.id.clone(), value),
        )
    });
}

/// Registers executable Lua constructors generated from the component profile.
pub fn register_generated_executable_bindings(lua: &Lua) -> mlua::Result<()> {
    let ui: Option<mlua::Table> = lua.globals().get("ui")?;
    let scene: Option<mlua::Table> = lua.globals().get("scene")?;
    let ui_find: Option<mlua::Function> = ui.as_ref().and_then(|table| table.get("find").ok());
    let scene_find: Option<mlua::Function> =
        scene.as_ref().and_then(|table| table.get("find").ok());
    if let (Some(table), Some(finder)) = (ui.as_ref(), ui_find.as_ref()) {
        let finder = finder.clone();
        table.set(
            "node",
            lua.create_function(move |_, id: String| finder.call::<mlua::Value>(id))?,
        )?;
    }
    if let (Some(table), Some(finder)) = (ui.as_ref(), ui_find.as_ref()) {
        let finder = finder.clone();
        table.set(
            "widget",
            lua.create_function(move |_, id: String| finder.call::<mlua::Value>(id))?,
        )?;
    }
    if let (Some(table), Some(finder)) = (ui.as_ref(), ui_find.as_ref()) {
        let finder = finder.clone();
        table.set(
            "text",
            lua.create_function(move |_, id: String| finder.call::<mlua::Value>(id))?,
        )?;
    }
    if let (Some(table), Some(finder)) = (ui.as_ref(), ui_find.as_ref()) {
        let finder = finder.clone();
        table.set(
            "text_box",
            lua.create_function(move |_, id: String| finder.call::<mlua::Value>(id))?,
        )?;
    }
    if let (Some(table), Some(finder)) = (ui.as_ref(), ui_find.as_ref()) {
        let finder = finder.clone();
        table.set(
            "button",
            lua.create_function(move |_, id: String| finder.call::<mlua::Value>(id))?,
        )?;
    }
    if let (Some(table), Some(finder)) = (scene.as_ref(), scene_find.as_ref()) {
        let finder = finder.clone();
        table.set(
            "node",
            lua.create_function(move |_, id: String| finder.call::<mlua::Value>(id))?,
        )?;
    }
    if let (Some(table), Some(finder)) = (scene.as_ref(), scene_find.as_ref()) {
        let finder = finder.clone();
        table.set(
            "spatial",
            lua.create_function(move |_, id: String| finder.call::<mlua::Value>(id))?,
        )?;
    }
    if let (Some(table), Some(finder)) = (scene.as_ref(), scene_find.as_ref()) {
        let finder = finder.clone();
        table.set(
            "mesh",
            lua.create_function(move |_, id: String| finder.call::<mlua::Value>(id))?,
        )?;
    }
    if let (Some(table), Some(finder)) = (scene.as_ref(), scene_find.as_ref()) {
        let finder = finder.clone();
        table.set(
            "camera",
            lua.create_function(move |_, id: String| finder.call::<mlua::Value>(id))?,
        )?;
    }
    if let (Some(table), Some(finder)) = (ui.as_ref(), ui_find.as_ref()) {
        let finder = finder.clone();
        table.set(
            "toggle",
            lua.create_function(move |_, id: String| finder.call::<mlua::Value>(id))?,
        )?;
    }
    if let (Some(table), Some(finder)) = (ui.as_ref(), ui_find.as_ref()) {
        let finder = finder.clone();
        table.set(
            "selector",
            lua.create_function(move |_, id: String| finder.call::<mlua::Value>(id))?,
        )?;
    }
    if let (Some(table), Some(finder)) = (ui.as_ref(), ui_find.as_ref()) {
        let finder = finder.clone();
        table.set(
            "scroll_viewer",
            lua.create_function(move |_, id: String| finder.call::<mlua::Value>(id))?,
        )?;
    }
    if let (Some(table), Some(finder)) = (ui.as_ref(), ui_find.as_ref()) {
        let finder = finder.clone();
        table.set(
            "scroll_panel",
            lua.create_function(move |_, id: String| finder.call::<mlua::Value>(id))?,
        )?;
    }
    if let (Some(table), Some(finder)) = (ui.as_ref(), ui_find.as_ref()) {
        let finder = finder.clone();
        table.set(
            "progress_bar",
            lua.create_function(move |_, id: String| finder.call::<mlua::Value>(id))?,
        )?;
    }
    if let (Some(table), Some(finder)) = (ui.as_ref(), ui_find.as_ref()) {
        let finder = finder.clone();
        table.set(
            "popup",
            lua.create_function(move |_, id: String| finder.call::<mlua::Value>(id))?,
        )?;
    }
    if let (Some(table), Some(finder)) = (ui.as_ref(), ui_find.as_ref()) {
        let finder = finder.clone();
        table.set(
            "input",
            lua.create_function(move |_, id: String| finder.call::<mlua::Value>(id))?,
        )?;
    }
    if let (Some(table), Some(finder)) = (ui.as_ref(), ui_find.as_ref()) {
        let finder = finder.clone();
        table.set(
            "image",
            lua.create_function(move |_, id: String| finder.call::<mlua::Value>(id))?,
        )?;
    }
    if let (Some(table), Some(finder)) = (ui.as_ref(), ui_find.as_ref()) {
        let finder = finder.clone();
        table.set(
            "grid",
            lua.create_function(move |_, id: String| finder.call::<mlua::Value>(id))?,
        )?;
    }
    if let (Some(table), Some(finder)) = (ui.as_ref(), ui_find.as_ref()) {
        let finder = finder.clone();
        table.set(
            "canvas",
            lua.create_function(move |_, id: String| finder.call::<mlua::Value>(id))?,
        )?;
    }
    Ok(())
}

/// Backwards-compatible name for callers that only need generated component aliases.
pub fn register_generated_component_aliases(lua: &Lua) -> mlua::Result<()> {
    register_generated_executable_bindings(lua)
}
